name: 🪲 Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ![Bug banner](https://user-images.githubusercontent.com/70886462/213660864-86527af9-50ba-45c3-8052-ec2157a67ecf.png)
      
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "Oh! An unexpected feature 😮"
    validations:
      required: true
  - type: checkboxes
    id: reproduce
    attributes:
      label: Can your reproduce this bug ?
      description: Tell us if this is a one time bug or something recuring you can easily reproduce
      options:
        - label: I can reproduce this bug
          required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: if other, specify it in the other information area
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - other
  - type: dropdown
    id: platform
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - iOS
        - Android
        - other
  - type: textarea
    id: otherinformation
    attributes:
      label: More details on your platform ?
      description: Add additional details on the platform your are using like version number, recent updates, a specific context
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/avanade-talentagile/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
