name: 💡 feature request
description: Propose a new feature
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ![banner-ooh-1](https://user-images.githubusercontent.com/6351798/172678916-1e6448f8-2a8d-4e74-84c4-7b215f2d5408.png)
        
        Thanks for taking the time to share your idea to improve the product!
  - type: textarea
    id: description
    attributes:
      label: How can we help you?
      description: Tell us what would make our product more efficient, easy to use?
      placeholder: "Don't hesitate to give details, to include images or any additional support that my help"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/avanade-talentagile/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
