name: 🧑‍💻 Request VSCode env
description: Require a new VS Code environment for a training session
title: "[VSCode] Session"
labels: []
body:
- type: checkboxes
  attributes:
    label: Are you OK with usage rules
    description: https://github.com/orgs/avanade-talentagile/discussions/1
    options:
    - label: I agree with usage rules
      required: true
  id: iAgree
- type: input
  attributes:
    label: From
    description: Start date
  validations:
    required: true
  id: startDate
- type: input
  attributes:
    label: To
    description: End date
  validations:
    required: true
  id: endDate
- type: textarea
  attributes:
    label: Trainees
    description: Email of the trainees, one per line
  validations:
    required: true
  id: trainees
