name: Greetings

on:
  issues:
    types: [opened, edited]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: store issue body
      run: echo '${{ toJSON(github) }} > body.json
    - name: get issue detail
      shell: pwsh
      run: |
        # echo '${{ github.event.issue.title }}'
        # echo '${{ github.event.issue.body }}'
        $title = '${{ github.event.issue.title }}'
        $body = Get-Content body.json | ConvertFrom-Markdown | fl *


