name: Greetings

on: 
  issues:
    types: [opened, edited]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: get issue detail
      run: |
        echo '${{ toJSON(env) }}'
        echo '${{ toJSON(github) }}'
        echo '${{ github.event.issue.body }}'
        cat ${{ github.event_path }}
