name: Greetings

on:
  issues:
    types: [opened, edited]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    # - name: store issue body
    #   run: echo '${{ toJSON(github) }} > body.json
    - name: get issue detail
      shell: pwsh
      run: |
        $event = Get-Content ${{ github.event_path }} | ConvertFrom-Json
        $title = $event.event.issue.title
        $body = $event.event.issue.body
        $body = $body | ConvertFrom-Markdown | fl *
        