name: Greetings

on:
  issues:
    types: [opened, edited]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: get issue detail
      run: |
        # echo '${{ github.event.issue.title }}'
        # echo '${{ github.event.issue.body }}'
        $title = '${{ github.event.issue.title }}'
        $body = '${{ github.event.issue.body }}' | ConvertFrom-Markdown | fl *


      shell: pwsh

